/**
 * AI Insights hook.
 *
 * Reads AI-generated insight cards for a host (GET /api/v1/insights), filters
 * out user-dismissed cards (localStorage), and exposes dismiss / dismissAll /
 * refresh plus a `generate()` mutation that triggers on-demand regeneration
 * (POST /api/v1/insights/generate) and revalidates.
 *
 * Modeled on lib/swr/use-notifications.ts. Insights are not 30s-critical, so the
 * background refresh is slow and the UI primarily refreshes on demand.
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import type { InsightCard } from '@/lib/insights/types'

import { useCallback, useEffect, useMemo } from 'react'
import {
  clearCachedInsights,
  loadCachedInsights,
  saveCachedInsights,
} from '@/lib/insights/cached-insights'
import {
  dismissAllInsights,
  dismissInsight,
  filterActiveInsights,
} from '@/lib/insights/dismissed-insights'
import { generateParamsFromSettings } from '@/lib/insights/settings'
import { useInsightsSettings } from '@/lib/query/use-insights-settings'
import { apiFetch } from '@/lib/swr/api-fetch'
import { REFRESH_INTERVAL, visibilityAwareInterval } from '@/lib/swr/config'

interface InsightsResponse {
  insights: InsightCard[]
  count: number
}

/**
 * Hosts already auto-generated in this browser session.
 *
 * MODULE scope, deliberately: this hook is mounted by several components at
 * once (insights-panel, insights-strip, insights-popover). A `useRef` guard is
 * created fresh per mount, so each instance only ever deduplicated against
 * itself and all of them fired the mount-time generate in the same tick —
 * measured as 3 concurrent `POST /api/v1/insights/generate`, i.e. ~30
 * ClickHouse scans on a page load instead of ~10. Sharing one Set across
 * instances is what makes the guard actually hold.
 *
 * Still per-host (switching hosts generates once for the new host), and module
 * scope resets on reload, so a hard refresh can regenerate as before.
 */
const autoGeneratedHosts = new Set<number>()

/**
 * Claim the one auto-generation allowed for `hostId` this session.
 *
 * Returns true for the first caller and false for every later one. React runs
 * layout/passive effects sequentially within a commit, so three components
 * mounting in the same tick call this one after another and only the first
 * wins — which is precisely the deduplication the old per-instance ref could
 * not provide.
 */
export function claimAutoGenerate(hostId: number): boolean {
  if (autoGeneratedHosts.has(hostId)) return false
  autoGeneratedHosts.add(hostId)
  return true
}

/** Test seam: reset the session-scoped auto-generate guard. */
export function resetAutoGeneratedHosts(): void {
  autoGeneratedHosts.clear()
}

/** Stable empty default so an unresolved session query doesn't churn `merged`. */
const EMPTY_INSIGHTS: readonly InsightCard[] = []

export interface UseInsightsResult {
  readonly insights: readonly InsightCard[]
  readonly counts: { critical: number; warning: number; info: number }
  isLoading: boolean
  isGenerating: boolean
  error?: Error
  refresh: () => void
  generate: () => void
  dismiss: (insight: InsightCard) => void
  dismissAll: () => void
}

export function useInsights(hostId: number): UseInsightsResult {
  const queryClient = useQueryClient()
  const { settings } = useInsightsSettings()
  const { window: readWindow } = settings

  // The read window is part of the cache key so changing it refetches.
  const queryKey = useMemo(
    () => [`/api/v1/insights?host=${hostId}`, readWindow],
    [hostId, readWindow]
  )

  const { data, error, isLoading } = useQuery<InsightsResponse>({
    queryKey,
    queryFn: async () => {
      const params = new URLSearchParams({
        host: String(hostId),
        since: readWindow,
      })
      const res = await apiFetch(`/api/v1/insights?${params.toString()}`)
      if (!res.ok) throw new Error('Failed to fetch insights')
      return res.json()
    },
    refetchInterval: visibilityAwareInterval(REFRESH_INTERVAL.SLOW_2M),
    staleTime: 60_000,
    retry: 1,
  })

  const invalidate = useCallback(
    () => queryClient.invalidateQueries({ queryKey }),
    [queryClient, queryKey]
  )

  // Insights from the most recent generate() call, seeded from localStorage as
  // a fallback for when the server-side findings store is empty (e.g. a
  // read-only ClickHouse monitoring connection).
  //
  // Held in the query cache rather than component state so every mounted
  // consumer shares one copy. With per-instance `useState`, only whichever
  // instance happened to run generate() saw the result — fine while all three
  // generated, but not once the auto-generate guard is shared (see
  // `autoGeneratedHosts`), because then the other panels would render empty
  // whenever the server store had nothing to return.
  const sessionKey = useMemo(() => ['insights-session', hostId], [hostId])
  const { data: sessionInsights = EMPTY_INSIGHTS } = useQuery<
    readonly InsightCard[]
  >({
    queryKey: sessionKey,
    queryFn: () => loadCachedInsights(hostId),
    staleTime: Number.POSITIVE_INFINITY,
    gcTime: Number.POSITIVE_INFINITY,
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
    // localStorage is client-only; keep SSR output identical to before.
    enabled: typeof window !== 'undefined',
  })

  const setSessionInsights = useCallback(
    (next: readonly InsightCard[]) =>
      queryClient.setQueryData(sessionKey, next),
    [queryClient, sessionKey]
  )

  const generateMutation = useMutation({
    // `auto` marks the mount-time generation: it forces `enrich=false` so the
    // panel populates from the deterministic collector copy without spending an
    // LLM enrichment call. `force` bypasses the server-side min-interval throttle
    // — the manual "Refresh" passes force:true; the auto-generate-on-mount effect
    // passes auto:true, force:false so a recently-generated host reuses stored
    // insights without re-running the ~10 ClickHouse scans.
    mutationFn: async ({
      auto = false,
      force = true,
    }: {
      auto?: boolean
      force?: boolean
    } = {}): Promise<InsightsResponse> => {
      const effectiveSettings = auto ? { ...settings, enrich: false } : settings
      const params = generateParamsFromSettings(hostId, effectiveSettings, {
        force,
      })
      const res = await apiFetch(`/api/v1/insights/generate?${params}`, {
        method: 'POST',
      })
      if (!res.ok) throw new Error('Failed to generate insights')
      return res.json()
    },
    onSuccess: (result) => {
      const fresh = result?.insights ?? []
      setSessionInsights(fresh)
      // Persist to localStorage as a cross-reload fallback regardless of
      // whether the server-side store accepted the write.
      saveCachedInsights(hostId, fresh)
      invalidate()
    },
  })

  // Merge persisted (read) + freshly generated / localStorage-cached (session);
  // de-dupe by stable key with the just-generated copy winning. Then drop
  // user-dismissed cards.
  const merged = useMemo(() => {
    const byKey = new Map<string, InsightCard>()
    for (const i of data?.insights ?? []) byKey.set(i.key, i)
    for (const i of sessionInsights) byKey.set(i.key, i)
    return Array.from(byKey.values())
  }, [data, sessionInsights])

  const insights = filterActiveInsights(merged)

  // Auto-generate once per host per session when nothing is cached or stored, so
  // the panel renders insights on load instead of an empty CTA. Gated on the
  // unfiltered `merged` set + the module-level per-host guard so it never loops
  // and never fights a user's "dismiss all" (which leaves merged non-empty).
  useEffect(() => {
    if (isLoading || generateMutation.isPending) return
    if (merged.length > 0) return
    if (!claimAutoGenerate(hostId)) return
    // Auto-generation respects the server-side throttle (force: false) so a
    // reopen within the min-interval reuses stored insights instead of re-running
    // the collect scans. And auto: true is passed to force enrich=false to skip
    // the LLM call.
    generateMutation.mutate({ auto: true, force: false })
  }, [isLoading, merged.length, hostId, generateMutation])

  const counts = insights.reduce(
    (acc, i) => {
      acc[i.severity] += 1
      return acc
    },
    { critical: 0, warning: 0, info: 0 }
  )

  const dismiss = useCallback(
    (insight: InsightCard) => {
      dismissInsight(insight)
      invalidate()
    },
    [invalidate]
  )

  const dismissAll = useCallback(() => {
    dismissAllInsights(insights)
    setSessionInsights([])
    // Also clear the localStorage fallback so dismissed insights don't
    // re-appear on the next page load before the server is queried.
    clearCachedInsights(hostId)
    invalidate()
  }, [insights, hostId, invalidate, setSessionInsights])

  return {
    insights,
    counts,
    isLoading,
    isGenerating: generateMutation.isPending,
    error: error ?? undefined,
    refresh: invalidate,
    // Manual user action -> force past the server-side throttle for an immediate
    // regeneration, and run enrichment (auto: false).
    generate: () => generateMutation.mutate({ auto: false, force: true }),
    dismiss,
    dismissAll,
  }
}
