/**
 * PeerDB AI Insights hook.
 *
 * The PeerDB analog of `use-postgres-insights.ts`, and of `use-insights.ts` for
 * ClickHouse. Reads cards from `GET /api/v1/insights/peerdb`, auto-generates
 * once per session when nothing is stored (respecting the server throttle),
 * filters user-dismissed cards through the same shared localStorage keys, and
 * exposes dismiss / refresh / generate.
 *
 * ## Why PeerDB findings are page-local, not in the global strip
 *
 * The shared surfaces (`useInsights` → `insights-strip` / `insights-panel` /
 * `insights-popover`) read `/api/v1/insights` and resolve against a **ClickHouse
 * `hostId`**. A PeerDB finding has no ClickHouse host: it is stored under the
 * reserved host key `peerdbInsightStoreHostId(0)` and belongs to the
 * env-wide PeerDB deployment, not to any host in the host list. Routing it
 * through the global panel would mean a `?host=` dimension that does not apply,
 * and `/insights` (whose charts are ClickHouse-only — see
 * `lib/insights/insight-charts.ts`) would render unrelated charts for it.
 *
 * So PeerDB findings render on the `/peerdb` surface, where the routing
 * dimension is the PeerDB connection. The decision is deliberate, not an
 * omission: mixing engines into one strip would either mislead the host
 * dimension or ship a chart-less card.
 *
 * Deliberately leaner than `useInsights` — no per-user settings, model picker,
 * or localStorage cache — matching the Postgres pair exactly.
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import type { InsightCard } from '@/lib/insights/types'

import { useCallback, useEffect, useMemo, useRef } from 'react'
import {
  dismissAllInsights,
  dismissInsight,
  filterActiveInsights,
} from '@/lib/insights/dismissed-insights'
import { apiFetch } from '@/lib/swr/api-fetch'
import { REFRESH_INTERVAL, visibilityAwareInterval } from '@/lib/swr/config'

interface PeerDBInsightsResponse {
  insights: InsightCard[]
  count: number
  /**
   * Present (with a `reason`) when the deployment has no PeerDB configured.
   * The route answers 200 with an empty, flagged payload rather than an error,
   * so the panel can distinguish "nothing to say" from "no PeerDB here".
   */
  unavailable?: { reason: string; message: string }
}

export const PEERDB_INSIGHTS_URL = '/api/v1/insights/peerdb'

export interface UsePeerDBInsightsResult {
  readonly insights: readonly InsightCard[]
  readonly counts: { critical: number; warning: number; info: number }
  isLoading: boolean
  isGenerating: boolean
  /** True when PeerDB is not configured on this deployment. */
  isUnavailable: boolean
  refresh: () => void
  generate: () => void
  dismiss: (insight: InsightCard) => void
  dismissAll: () => void
}

export function usePeerDBInsights(): UsePeerDBInsightsResult {
  const queryClient = useQueryClient()
  const queryKey = useMemo(() => [PEERDB_INSIGHTS_URL] as const, [])

  const { data, isLoading } = useQuery<PeerDBInsightsResponse>({
    queryKey,
    queryFn: async () => {
      const res = await apiFetch(PEERDB_INSIGHTS_URL)
      if (!res.ok) throw new Error('Failed to fetch PeerDB insights')
      return res.json()
    },
    refetchInterval: visibilityAwareInterval(REFRESH_INTERVAL.SLOW_2M),
    staleTime: 60_000,
    retry: 1,
  })

  const invalidate = useCallback(
    () => queryClient.invalidateQueries({ queryKey }),
    [queryClient, queryKey]
  )

  const generateMutation = useMutation({
    mutationFn: async ({
      force = true,
    }: {
      force?: boolean
    } = {}): Promise<PeerDBInsightsResponse> => {
      const params = new URLSearchParams()
      if (force) params.set('force', 'true')
      else params.set('enrich', 'false')
      const res = await apiFetch(
        `${PEERDB_INSIGHTS_URL}?${params.toString()}`,
        { method: 'POST' }
      )
      if (!res.ok) throw new Error('Failed to generate PeerDB insights')
      return res.json()
    },
    onSuccess: () => invalidate(),
  })

  const merged = useMemo(() => {
    const byKey = new Map<string, InsightCard>()
    for (const i of data?.insights ?? []) byKey.set(i.key, i)
    return Array.from(byKey.values())
  }, [data])

  const insights = filterActiveInsights(merged)
  const isUnavailable = data?.unavailable !== undefined

  // Auto-generate once per session when nothing is stored, so the panel
  // populates on load. Respects the server throttle (`force=false`) and never
  // fires against an unconfigured deployment.
  const autoGenerated = useRef(false)
  useEffect(() => {
    if (isLoading || generateMutation.isPending) return
    if (isUnavailable) return
    if (merged.length > 0) return
    if (autoGenerated.current) return
    autoGenerated.current = true
    generateMutation.mutate({ force: false })
  }, [isLoading, merged.length, isUnavailable, generateMutation])

  const counts = insights.reduce(
    (acc, i) => {
      acc[i.severity] += 1
      return acc
    },
    { critical: 0, warning: 0, info: 0 }
  )

  const dismiss = useCallback(
    (insight: InsightCard) => {
      dismissInsight(insight)
      invalidate()
    },
    [invalidate]
  )

  const dismissAll = useCallback(() => {
    dismissAllInsights(insights)
    invalidate()
  }, [insights, invalidate])

  return {
    insights,
    counts,
    isLoading,
    isGenerating: generateMutation.isPending,
    isUnavailable,
    refresh: invalidate,
    generate: () => generateMutation.mutate({ force: true }),
    dismiss,
    dismissAll,
  }
}
