import data from '@/generated/docs-data/alert-rules.json'

/* Generated by scripts/gen-docs-data.ts — do not hand-edit the data. */

export interface AlertRuleFix {
  id: string
  kind: string
  label: string
  description: string | null
  url: string | null
  sql: string | null
}

export interface AlertRule {
  id: string
  title: string
  description: string
  category: string
  thresholds: { warning: number; critical: number }
  sampleLabel: string | null
  tableCheck: string | null
  optional: boolean
  sql: string | null
  commonCauses: string[]
  link: string | null
  fix: AlertRuleFix[]
}

export interface CompoundRule {
  id: string
  title: string
  description: string
  category: string
  depends: string[]
}

/** Rules grouped by category, categories and rules in stable order. */
export function groupRules(
  rules: readonly AlertRule[]
): [string, AlertRule[]][] {
  const groups = new Map<string, AlertRule[]>()
  for (const r of rules) {
    const list = groups.get(r.category) ?? []
    list.push(r)
    groups.set(r.category, list)
  }
  return [...groups.entries()].sort(([a], [b]) => (a < b ? -1 : 1))
}

function Sql({ sql, summary }: { sql: string; summary: string }) {
  return (
    <details className="mt-2 rounded-md border border-fd-border">
      <summary className="cursor-pointer px-2.5 py-1 text-xs text-fd-muted-foreground hover:text-fd-foreground">
        {summary}
      </summary>
      <pre className="overflow-x-auto border-t border-fd-border bg-fd-background p-3 text-[12px] leading-relaxed">
        <code>{sql}</code>
      </pre>
    </details>
  )
}

function RuleCard({ rule }: { rule: AlertRule }) {
  return (
    <li id={`rule-${rule.id}`} className="px-4 py-3">
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="font-medium text-fd-foreground">{rule.title}</span>
        <code className="text-[11px] text-fd-muted-foreground">{rule.id}</code>
        <span className="ml-auto flex gap-1 text-[11px]">
          <span className="rounded bg-amber-500/10 px-1.5 py-0.5 text-amber-700 dark:text-amber-300">
            warning ≥ {rule.thresholds.warning}
          </span>
          <span className="rounded bg-red-500/10 px-1.5 py-0.5 text-red-700 dark:text-red-300">
            critical ≥ {rule.thresholds.critical}
          </span>
        </span>
      </div>
      <p className="mt-1 text-sm text-fd-muted-foreground">
        {rule.description}
      </p>
      <dl className="mt-1.5 grid grid-cols-[auto_1fr] gap-x-3 gap-y-0.5 text-xs">
        {rule.tableCheck && (
          <>
            <dt className="text-fd-muted-foreground">Requires</dt>
            <dd>
              <code>{rule.tableCheck}</code>
              {rule.optional && (
                <span className="text-fd-muted-foreground">
                  {' '}
                  (skipped when missing)
                </span>
              )}
            </dd>
          </>
        )}
        {rule.sampleLabel && (
          <>
            <dt className="text-fd-muted-foreground">Alert reads</dt>
            <dd>{rule.sampleLabel}</dd>
          </>
        )}
      </dl>
      {rule.commonCauses.length > 0 && (
        <ul className="mt-1.5 list-disc pl-5 text-xs text-fd-muted-foreground">
          {rule.commonCauses.map((c) => (
            <li key={c}>{c}</li>
          ))}
        </ul>
      )}
      {rule.fix.length > 0 && (
        <div className="mt-1.5 flex flex-wrap gap-x-3 gap-y-1 text-xs">
          {rule.fix
            .filter((f) => f.url)
            .map((f) => (
              <a key={f.id} href={f.url ?? undefined} className="underline">
                {f.label}
              </a>
            ))}
        </div>
      )}
      {rule.sql && <Sql sql={rule.sql} summary="Rule SQL" />}
      {rule.fix
        .filter((f) => f.sql)
        .map((f) => (
          <Sql key={f.id} sql={f.sql ?? ''} summary={f.label} />
        ))}
    </li>
  )
}

export function AlertRuleList({
  rules = data.rules as AlertRule[],
  compound = data.compound as CompoundRule[],
}: {
  rules?: AlertRule[]
  compound?: CompoundRule[]
}) {
  return (
    <div className="not-prose my-6 space-y-4">
      {groupRules(rules).map(([category, list]) => (
        <section
          key={category}
          className="overflow-hidden rounded-xl border border-fd-border bg-fd-card"
        >
          <h4 className="border-b border-fd-border px-4 py-2 text-[11px] font-semibold uppercase tracking-widest text-fd-muted-foreground">
            {category}
          </h4>
          <ul className="divide-y divide-fd-border">
            {list.map((r) => (
              <RuleCard key={r.id} rule={r} />
            ))}
          </ul>
        </section>
      ))}
      {compound.length > 0 && (
        <section className="overflow-hidden rounded-xl border border-fd-border bg-fd-card">
          <h4 className="border-b border-fd-border px-4 py-2 text-[11px] font-semibold uppercase tracking-widest text-fd-muted-foreground">
            compound
          </h4>
          <ul className="divide-y divide-fd-border">
            {compound.map((c) => (
              <li key={c.id} id={`rule-${c.id}`} className="px-4 py-3">
                <div className="flex flex-wrap items-center gap-1.5">
                  <span className="font-medium text-fd-foreground">
                    {c.title}
                  </span>
                  <code className="text-[11px] text-fd-muted-foreground">
                    {c.id}
                  </code>
                </div>
                <p className="mt-1 text-sm text-fd-muted-foreground">
                  {c.description}
                </p>
                <p className="mt-1 text-xs text-fd-muted-foreground">
                  Fires when all of:{' '}
                  {c.depends.map((d, i) => (
                    <span key={d}>
                      {i > 0 && ', '}
                      <a href={`#rule-${d}`} className="underline">
                        <code>{d}</code>
                      </a>
                    </span>
                  ))}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  )
}
