'use client'

import { CheckIcon, CopyIcon, SearchIcon } from 'lucide-react'

import { useMemo, useState } from 'react'
import data from '@/generated/docs-data/env-vars.json'
import { copyToClipboard } from '@/lib/clipboard'

/* Generated by scripts/gen-docs-data.ts — do not hand-edit the data. */

export interface EnvVar {
  name: string
  prefix: string
  inEnvExample: boolean
  exampleDefault: string | null
}

/** Unique name prefixes (CHM, CLICKHOUSE, ...), sorted — the category chips. */
export function envCategories(vars: readonly EnvVar[]): string[] {
  return [...new Set(vars.map((v) => v.prefix))].sort()
}

export function filterEnvVars(
  vars: readonly EnvVar[],
  query: string,
  category: string | null
): EnvVar[] {
  const q = query.trim().toUpperCase()
  return vars.filter(
    (v) =>
      (category === null || v.prefix === category) &&
      (q === '' || v.name.includes(q))
  )
}

function CopyName({ name }: { name: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      type="button"
      aria-label={`Copy ${name}`}
      onClick={async () => {
        if (await copyToClipboard(name)) {
          setCopied(true)
          setTimeout(() => setCopied(false), 1500)
        }
      }}
      className="shrink-0 rounded p-1 text-fd-muted-foreground transition-colors hover:bg-fd-muted hover:text-fd-foreground"
    >
      {copied ? (
        <CheckIcon className="size-3.5 text-emerald-500" />
      ) : (
        <CopyIcon className="size-3.5" />
      )}
    </button>
  )
}

export function EnvVarTable({
  vars = data.vars as EnvVar[],
}: {
  vars?: EnvVar[]
}) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState<string | null>(null)
  const categories = useMemo(() => envCategories(vars), [vars])
  const rows = useMemo(
    () => filterEnvVars(vars, query, category),
    [vars, query, category]
  )

  const chip = (active: boolean) =>
    `rounded-full border px-2.5 py-0.5 text-xs transition-colors ${
      active
        ? 'border-fd-primary bg-fd-primary text-fd-primary-foreground'
        : 'border-fd-border text-fd-muted-foreground hover:bg-fd-muted hover:text-fd-foreground'
    }`

  return (
    <div className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-fd-card">
      <div className="space-y-3 border-b border-fd-border px-4 py-3">
        <label className="flex items-center gap-2 rounded-md border border-fd-border bg-fd-background px-2.5 py-1.5">
          <SearchIcon className="size-3.5 text-fd-muted-foreground" />
          <span className="sr-only">Search environment variables</span>
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={`Search ${vars.length} variables`}
            className="w-full bg-transparent text-sm outline-none placeholder:text-fd-muted-foreground"
          />
        </label>
        <div className="flex flex-wrap gap-1.5">
          <button
            type="button"
            className={chip(category === null)}
            aria-pressed={category === null}
            onClick={() => setCategory(null)}
          >
            All
          </button>
          {categories.map((c) => (
            <button
              key={c}
              type="button"
              className={chip(category === c)}
              aria-pressed={category === c}
              onClick={() => setCategory(category === c ? null : c)}
            >
              {c}
            </button>
          ))}
        </div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-fd-border text-left text-xs text-fd-muted-foreground">
              <th className="px-4 py-2 font-medium">Name</th>
              <th className="px-4 py-2 font-medium">In .env.example</th>
              <th className="px-4 py-2 font-medium">Default</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((v) => (
              <tr
                key={v.name}
                className="border-b border-fd-border last:border-0"
              >
                <td className="px-4 py-1.5">
                  <span className="flex items-center gap-1">
                    <code className="text-[13px]">{v.name}</code>
                    <CopyName name={v.name} />
                  </span>
                </td>
                <td className="px-4 py-1.5 text-fd-muted-foreground">
                  {v.inEnvExample ? 'yes' : '—'}
                </td>
                <td className="px-4 py-1.5">
                  {v.exampleDefault === null ? (
                    <span className="text-fd-muted-foreground">—</span>
                  ) : (
                    <code className="text-[13px]">{v.exampleDefault}</code>
                  )}
                </td>
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td
                  colSpan={3}
                  className="px-4 py-6 text-center text-fd-muted-foreground"
                >
                  No variables match.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
