'use client'

import { useMemo, useState } from 'react'
import data from '@/generated/docs-data/agent-tools.json'

/* Generated by scripts/gen-docs-data.ts — do not hand-edit the data. */

export interface AgentTool {
  name: string
  category: string | null
  summary: string | null
  description: string | null
  core: boolean
  envGate: string | null
}

export function toolCategories(tools: readonly AgentTool[]): string[] {
  return [...new Set(tools.map((t) => t.category ?? 'uncategorized'))].sort()
}

export function filterTools(
  tools: readonly AgentTool[],
  category: string | null
): AgentTool[] {
  if (category === null) return [...tools]
  return tools.filter((t) => (t.category ?? 'uncategorized') === category)
}

export function ToolCatalog({
  tools = data.tools as AgentTool[],
}: {
  tools?: AgentTool[]
}) {
  const [category, setCategory] = useState<string | null>(null)
  const categories = useMemo(() => toolCategories(tools), [tools])
  const rows = useMemo(() => filterTools(tools, category), [tools, category])

  const chip = (active: boolean) =>
    `rounded-full border px-2.5 py-0.5 text-xs transition-colors ${
      active
        ? 'border-fd-primary bg-fd-primary text-fd-primary-foreground'
        : 'border-fd-border text-fd-muted-foreground hover:bg-fd-muted hover:text-fd-foreground'
    }`

  return (
    <div className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-fd-card">
      <div className="flex flex-wrap gap-1.5 border-b border-fd-border px-4 py-3">
        <button
          type="button"
          className={chip(category === null)}
          aria-pressed={category === null}
          onClick={() => setCategory(null)}
        >
          All ({tools.length})
        </button>
        {categories.map((c) => (
          <button
            key={c}
            type="button"
            className={chip(category === c)}
            aria-pressed={category === c}
            onClick={() => setCategory(category === c ? null : c)}
          >
            {c}
          </button>
        ))}
      </div>
      <ul className="divide-y divide-fd-border">
        {rows.map((t) => (
          <li key={t.name} className="px-4 py-2.5">
            <div className="flex flex-wrap items-center gap-1.5">
              <code className="text-[13px] font-medium">{t.name}</code>
              {t.core && (
                <span className="rounded bg-fd-primary/10 px-1.5 py-0.5 text-[10px] font-medium text-fd-primary">
                  core
                </span>
              )}
              {t.envGate && (
                <span
                  className="rounded border border-amber-500/40 bg-amber-500/10 px-1.5 py-0.5 text-[10px] font-medium text-amber-700 dark:text-amber-300"
                  title={`Only available when ${t.envGate}=true`}
                >
                  {t.envGate}=true
                </span>
              )}
              <span className="ml-auto text-[11px] text-fd-muted-foreground">
                {t.category ?? 'uncategorized'}
              </span>
            </div>
            {(t.summary ?? t.description) && (
              <p className="mt-1 text-sm text-fd-muted-foreground">
                {t.summary ?? t.description}
              </p>
            )}
          </li>
        ))}
      </ul>
    </div>
  )
}
