import data from '@/generated/docs-data/version-matrix.json'

/* Generated by scripts/gen-docs-data.ts — do not hand-edit the data. */

export interface VersionMatrixData {
  minimumSupportedVersion: string
  ltsVersions: string[]
  supportedMajorVersions: number[]
  configs: { name: string; since: string[] }[]
}

/** Every distinct `since` version across configs, oldest first. */
export function sinceColumns(configs: VersionMatrixData['configs']): string[] {
  const all = new Set(configs.flatMap((c) => c.since))
  return [...all].sort((a, b) => {
    const pa = a.split('.').map(Number)
    const pb = b.split('.').map(Number)
    return (pa[0] - pb[0]) * 1000 + ((pa[1] ?? 0) - (pb[1] ?? 0))
  })
}

export function VersionMatrix({
  matrix = data as VersionMatrixData,
}: {
  matrix?: VersionMatrixData
}) {
  const columns = sinceColumns(matrix.configs)
  return (
    <div className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-fd-card">
      <div className="space-y-1 border-b border-fd-border px-4 py-3 text-sm">
        <p>
          Minimum supported ClickHouse version:{' '}
          <strong>{matrix.minimumSupportedVersion}</strong>
        </p>
        <p className="text-xs text-fd-muted-foreground">
          LTS: {matrix.ltsVersions.join(', ')} · Major series:{' '}
          {matrix.supportedMajorVersions.join(', ')}
        </p>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-fd-border text-fd-muted-foreground">
              <th className="sticky left-0 bg-fd-card px-3 py-2 text-left font-medium">
                Query
              </th>
              {columns.map((v) => (
                <th key={v} className="px-2 py-2 text-center font-medium">
                  {v}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {matrix.configs.map((c) => (
              <tr
                key={c.name}
                className="border-b border-fd-border last:border-0"
              >
                <td className="sticky left-0 bg-fd-card px-3 py-1.5">
                  <code>{c.name}</code>
                </td>
                {columns.map((v) => (
                  <td key={v} className="px-2 py-1.5 text-center">
                    {c.since.includes(v) ? (
                      <span
                        className="text-fd-primary"
                        title={`SQL variant for ClickHouse ${v}+`}
                      >
                        ●
                      </span>
                    ) : null}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="border-t border-fd-border px-4 py-2 text-xs text-fd-muted-foreground">
        ● marks a version where the query switches to a new SQL variant. The
        dashboard picks the newest variant at or below your server version.
      </p>
    </div>
  )
}
