/**
 * Health tab charts - errors, connections, and coordination
 */

import {
  ChartCancelledQueries,
  ChartConnectionsPool,
  ChartCrashFrequency,
  ChartErrorRateOverTime,
  ChartFailedQueryCount,
  ChartFailedQueryCountByUser,
  ChartKeeperException,
  ChartLogLevelDistribution,
  ChartOomKilledQueries,
  ChartSlowQueryOccurrences,
  ChartZookeeperRequests,
  ChartZookeeperWait,
} from '../-charts-lazy'
import type { OverviewChartConfig } from './types'

export const HEALTH_TAB_CHARTS: OverviewChartConfig[] = [
  {
    id: 'failed-queries-health',
    component: ChartFailedQueryCount,
    title: 'Failed Queries',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/failed-queries',
  },
  {
    id: 'keeper-exception',
    component: ChartKeeperException,
    title: 'ZooKeeper/Keeper Exceptions',
    className: 'w-full h-full',
    type: 'bar',
    href: '/zookeeper',
  },
  {
    id: 'zookeeper-wait',
    component: ChartZookeeperWait,
    title: 'ZooKeeper Wait Time',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'bar',
    href: '/zookeeper',
  },
  {
    id: 'zookeeper-requests',
    component: ChartZookeeperRequests,
    title: 'ZooKeeper Requests',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'bar',
    href: '/zookeeper',
  },
  {
    id: 'connections-pool',
    component: ChartConnectionsPool,
    title: 'Connection Pool',
    lastHours: 24,
    interval: 'toStartOfFiveMinutes',
    className: 'w-full h-full',
    type: 'area',
    href: '/charts?name=connections-http,connections-interserver',
  },
  {
    id: 'oom-killed-queries',
    component: ChartOomKilledQueries,
    title: 'OOM Killed Queries',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/failed-queries',
  },
  {
    id: 'cancelled-queries',
    component: ChartCancelledQueries,
    title: 'Cancelled Queries',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'custom',
    href: '/failed-queries',
  },
  {
    id: 'slow-query-occurrences',
    component: ChartSlowQueryOccurrences,
    title: 'Slow Query Occurrences',
    className: 'w-full h-full',
    type: 'bar',
    href: '/slow-queries',
  },
  {
    id: 'failed-query-count-by-user-health',
    component: ChartFailedQueryCountByUser,
    title: 'Failed Queries by User',
    className: 'w-full h-full',
    type: 'bar',
    href: '/failed-queries',
  },
  {
    id: 'crash-frequency',
    component: ChartCrashFrequency,
    title: 'Crash Frequency',
    lastHours: 24 * 30,
    interval: 'toStartOfDay',
    className: 'w-full h-full',
    type: 'bar',
    href: '/logs',
  },
  {
    id: 'error-rate-over-time',
    component: ChartErrorRateOverTime,
    title: 'Error Rate Over Time',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/logs',
  },
  {
    id: 'log-level-distribution',
    component: ChartLogLevelDistribution,
    title: 'Log Level Distribution',
    className: 'w-full h-full',
    type: 'custom',
    href: '/logs',
  },
]
