/**
 * Overview tab charts - at-a-glance health metrics
 */

import {
  ChartConnectionsPool,
  ChartCPUUsage,
  ChartDiskIOThroughput,
  ChartDisksUsage,
  ChartDiskUsage,
  ChartFailedQueryCount,
  ChartMemoryUsage,
  ChartMergeCount,
  ChartMutationProgress,
  ChartNewPartsCreated,
  ChartQueryCount,
  ChartQueryCountByUser,
  ChartQueryCountHeatmap,
  ChartQueryDuration,
  ChartQueryDurationPercentiles,
  ChartThreadUtilization,
  ChartTopMemoryQueries,
  ChartTopTableSize,
} from '../-charts-lazy'
import type { OverviewChartConfig } from './types'

export const OVERVIEW_TAB_CHARTS: OverviewChartConfig[] = [
  {
    id: 'query-count-heatmap-overview',
    component: ChartQueryCountHeatmap,
    title: 'Query Activity Heatmap',
    className: 'w-full',
    type: 'custom',
    fullWidth: true,
  },
  {
    id: 'query-count-24h',
    component: ChartQueryCount,
    title: 'Query Count',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/history-queries',
  },
  {
    id: 'query-count-by-user-24h',
    component: ChartQueryCountByUser,
    title: 'Query Count by User',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'bar',
    href: '/history-queries',
  },
  {
    id: 'query-duration',
    component: ChartQueryDuration,
    title: 'Avg Query Duration',
    lastHours: 24 * 14,
    interval: 'toStartOfDay',
    className: 'w-full h-full',
    type: 'bar',
    href: '/history-queries',
  },
  {
    id: 'query-duration-percentiles-overview',
    component: ChartQueryDurationPercentiles,
    title: 'Query Duration p50/p95/p99',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/history-queries',
  },
  {
    id: 'failed-query-count',
    component: ChartFailedQueryCount,
    title: 'Failed Queries',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/failed-queries',
  },
  {
    id: 'memory-usage',
    component: ChartMemoryUsage,
    title: 'Memory Usage',
    className: 'w-full h-full',
    interval: 'toStartOfTenMinutes',
    lastHours: 24,
    type: 'area',
    href: '/metrics',
  },
  {
    id: 'cpu-usage',
    component: ChartCPUUsage,
    title: 'CPU Usage',
    className: 'w-full h-full',
    interval: 'toStartOfTenMinutes',
    lastHours: 24,
    type: 'area',
    href: '/metrics',
  },
  {
    id: 'connections-pool-overview',
    component: ChartConnectionsPool,
    title: 'Connection Pool',
    lastHours: 24,
    interval: 'toStartOfFiveMinutes',
    className: 'w-full h-full',
    type: 'area',
    href: '/charts?name=connections-http,connections-interserver',
  },
  {
    id: 'disk-usage-breakdown-overview',
    component: ChartDiskUsage,
    title: 'Disk Usage',
    // row-span-2 lets all disks render without an inner scrollbar
    className: 'w-full h-full row-span-2',
    type: 'custom',
    href: '/disks',
  },
  {
    id: 'disks-usage-overview',
    component: ChartDisksUsage,
    className: 'w-full h-full',
    title: 'Disks Usage Trend',
    interval: 'toStartOfDay',
    lastHours: 24 * 30,
    type: 'area',
    href: '/disks',
  },
  {
    id: 'top-table-size',
    component: ChartTopTableSize,
    title: 'Top Tables by Size',
    className: 'w-full h-full row-span-2',
    type: 'custom',
    href: '/tables-overview',
  },
  {
    id: 'new-parts-created-overview',
    component: ChartNewPartsCreated,
    title: 'New Parts Created',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'bar',
    href: '/merge-performance',
  },
  {
    id: 'merge-count-overview',
    component: ChartMergeCount,
    title: 'Merge and PartMutation',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'custom',
    href: '/merges',
  },
  {
    id: 'mutation-progress-overview',
    component: ChartMutationProgress,
    title: 'Mutation Progress',
    className: 'w-full h-full',
    type: 'custom',
    href: '/mutations',
  },
  {
    id: 'top-memory-queries',
    component: ChartTopMemoryQueries,
    title: 'Top Memory Queries',
    className: 'w-full h-full row-span-2',
    type: 'custom',
    href: '/expensive-queries',
  },
  {
    id: 'disk-io-throughput',
    component: ChartDiskIOThroughput,
    title: 'Disk I/O Throughput',
    lastHours: 24,
    interval: 'toStartOfFifteenMinutes',
    className: 'w-full h-full',
    type: 'area',
    href: '/disks',
  },
  {
    id: 'thread-utilization-overview',
    component: ChartThreadUtilization,
    title: 'Thread Utilization',
    lastHours: 24,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/metrics',
  },
]
