/**
 * Queries tab charts - query performance and patterns (detailed view)
 */

import type { OverviewChartConfig } from './types'

import {
  ChartInsertPerformance,
  ChartQueryCache,
  ChartQueryCacheUsage,
  ChartQueryCountByUser,
  ChartQueryCountHeatmap,
  ChartQueryDurationPercentiles,
  ChartQueryDurationTrend,
  ChartQueryMemory,
  ChartQueryType,
  ChartTopInserters,
  ChartTopQueryFingerprintsPerf,
} from '../-charts-lazy'

export const QUERIES_TAB_CHARTS: OverviewChartConfig[] = [
  {
    id: 'query-count-heatmap',
    component: ChartQueryCountHeatmap,
    title: 'Query Activity Heatmap',
    className: 'w-full',
    type: 'custom',
    fullWidth: true,
  },
  {
    id: 'query-count-14d',
    component: ChartQueryCountByUser,
    title: 'Query Count',
    lastHours: 24 * 14,
    interval: 'toStartOfDay',
    className: 'w-full h-full',
    type: 'bar',
    href: '/history-queries',
  },
  {
    id: 'query-memory',
    component: ChartQueryMemory,
    title: 'Avg Query Memory Usage',
    lastHours: 24 * 14,
    interval: 'toStartOfDay',
    className: 'w-full h-full',
    type: 'bar',
    href: '/expensive-queries',
  },
  {
    id: 'query-cache',
    component: ChartQueryCache,
    title: 'Query Cache Status',
    className: 'w-full h-full',
    type: 'metric',
    href: '/query-cache',
  },
  {
    id: 'query-cache-usage',
    component: ChartQueryCacheUsage,
    title: 'Query Cache Hit Rate',
    lastHours: 24 * 7,
    className: 'w-full h-full',
    type: 'custom',
    href: '/query-cache',
  },
  {
    id: 'query-type',
    component: ChartQueryType,
    title: 'Query Type Distribution',
    lastHours: 24,
    className: 'w-full h-full',
    type: 'custom',
    href: '/history-queries',
  },
  {
    id: 'query-duration-percentiles',
    component: ChartQueryDurationPercentiles,
    title: 'Query Duration Percentiles',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/history-queries',
  },
  {
    id: 'insert-performance',
    component: ChartInsertPerformance,
    title: 'Insert Performance',
    lastHours: 24,
    interval: 'toStartOfFifteenMinutes',
    className: 'w-full h-full',
    type: 'area',
    href: '/history-queries',
  },
  {
    id: 'query-duration-trend',
    component: ChartQueryDurationTrend,
    title: 'Query Duration Trend',
    lastHours: 24 * 7,
    interval: 'toStartOfHour',
    className: 'w-full h-full',
    type: 'area',
    href: '/history-queries',
  },
  {
    id: 'top-inserters',
    component: ChartTopInserters,
    title: 'Top Inserters',
    className: 'w-full h-full',
    type: 'custom',
    href: '/history-queries',
  },
  {
    id: 'top-query-fingerprints-perf',
    component: ChartTopQueryFingerprintsPerf,
    title: 'Top Query Fingerprints (Perf)',
    className: 'w-full h-full col-span-1 md:col-span-2 2xl:col-span-3',
    type: 'custom',
    href: '/history-queries',
  },
]
