/**
 * Storage tab charts - disk usage, tables, parts, backups
 */

import type { OverviewChartConfig } from './types'

import {
  ChartBackupSize,
  ChartCompressionRatio,
  ChartDataFreshness,
  ChartDiskSize,
  ChartDisksUsage,
  ChartDiskUsageByDatabase,
  ChartDiskUsageTrend,
  ChartNewPartsCreated,
  ChartPartitionPartHealth,
  ChartPartsPerTable,
  ChartStoragePolicies,
  ChartTopTableSize,
} from '../-charts-lazy'

export const STORAGE_TAB_CHARTS: OverviewChartConfig[] = [
  {
    id: 'disk-size',
    component: ChartDiskSize,
    // taller card: spans 2 rows so the headline + disk rows have room to breathe
    className: 'w-full h-full row-span-2',
    title: 'Disk Size',
    type: 'metric',
    href: '/disks',
  },
  {
    id: 'disks-usage',
    component: ChartDisksUsage,
    className: 'w-full h-full',
    title: 'Disks Usage',
    interval: 'toStartOfDay',
    lastHours: 24 * 30,
    type: 'area',
    href: '/disks',
  },
  {
    id: 'disk-usage-trend',
    component: ChartDiskUsageTrend,
    className: 'w-full h-full',
    title: 'Disk Usage Trend',
    interval: 'toStartOfDay',
    lastHours: 24 * 7,
    type: 'area',
    href: '/disks',
  },
  {
    id: 'compression-ratio',
    component: ChartCompressionRatio,
    className: 'w-full h-full',
    title: 'Compression Ratio',
    type: 'metric',
    href: '/tables-overview',
  },
  {
    id: 'data-freshness',
    component: ChartDataFreshness,
    className: 'w-full h-full',
    title: 'Data Freshness',
    interval: 'toStartOfDay',
    lastHours: 24 * 7,
    type: 'custom',
    href: '/tables-overview',
  },
  {
    id: 'top-table-size-storage',
    component: ChartTopTableSize,
    title: 'Top Tables by Size',
    className: 'w-full h-full',
    type: 'custom',
    href: '/tables-overview',
  },
  {
    id: 'new-parts-created',
    component: ChartNewPartsCreated,
    className: 'w-full h-full',
    title: 'New Parts Created',
    interval: 'toStartOfHour',
    lastHours: 24,
    type: 'bar',
    href: '/merge-performance',
  },
  {
    id: 'backup-size',
    component: ChartBackupSize,
    className: 'w-full h-full',
    title: 'Backup Size',
    chartClassName: 'h-[140px] sm:h-[160px]',
    type: 'metric',
    href: '/backups',
  },
  {
    id: 'disk-usage-by-database',
    component: ChartDiskUsageByDatabase,
    title: 'Disk Usage by Database',
    className: 'w-full h-full',
    type: 'bar',
    href: '/tables-overview',
  },
  {
    id: 'storage-policies',
    component: ChartStoragePolicies,
    title: 'Storage Policies',
    className: 'w-full h-full col-span-1 md:col-span-2 xl:col-span-3',
    type: 'table',
    href: '/disks',
  },
  {
    id: 'parts-per-table',
    component: ChartPartsPerTable,
    title: 'Parts per Table',
    className: 'w-full h-full',
    type: 'custom',
    href: '/tables-overview',
  },
  {
    id: 'partition-part-health',
    component: ChartPartitionPartHealth,
    title: 'Partition Part Health',
    className: 'w-full h-full',
    type: 'custom',
    href: '/tables-overview',
  },
]
